	<nav class="navbar navbar-inverse navbar-fixed-top">
		<nav class="navbar-inner">
			<div class="container">
				<button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="brand" href="#">BitCoin Store</a>
				<nav class="nav-collapse collapse">
					<ul class="nav">
						<li class="active"><a href="/">Home</a></li>
						<li><a href="/info">About BitCoin</a></li>
					</ul>
				</nav>
			</div>
		</nav>
	</nav>

	<header>
		<div class="container">
			<h1>BitCoin Store</h1>
			<p class="lead">
				Eindelijk een BitCoin winkel waar je met iDeal kan betalen!!!
			</p>
		</div>
	</header>