<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>BitCoin Store</title>
<!--[if lt IE 9]>
<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/css/bootstrap-combined.min.css">
<link href="styles/main.css" rel="stylesheet"/>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script	src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/js/bootstrap.min.js"></script>
</head>
<body>

	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				<button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="brand" href="#">BitCoin Store</a>
				<div class="nav-collapse collapse">
					<ul class="nav">
						<li class="active"><a href="/">Home</a></li>
						<li><a href="/info">About BitCoin</a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>

	<header>
		<div class="container">
			<h1>BitCoin Store</h1>
			<p class="lead">
				Eindelijk een BitCoin winkel waar je met iDeal kan betalen!!!
			</p>
		</div>
	</header>

	<div class="container">
		<div class="row">

			<article class="span9">
				<form class="form-horizontal" method="POST">
					<fieldset>
						<legend>Order BitCoins</legend>

						<div class="control-group">
							<label class="control-label" for="<?=$form->wallet->uid?>">Wallet</label>
							<div class="controls">
								<?=$form->wallet
												->setAttribute('class', 'span5')
												->setAttribute('placeholder', 'Wallet')
												->toHtml()
								?>
							</div>
						</div>

						<div class="control-group">
							<label class="control-label" for="<?=$form->number->uid?>">Bitcoins</label>
							<div class="controls">
								<?=$form->number
												->setAttribute('class', 'span5')
												->setAttribute('placeholder', 'Number of Bitcoins')
												->toHtml()
								?>
							</div>
						</div>

						<div class="control-group">
							<label class="control-label">Price per bitcoin</label>
							<div class="controls">
								<span class="uneditable-input span5" id="bitcoinsRate">
									<?=$form->rate?>
								</span>
							</div>
						</div>

						<div class="control-group">
							<label class="control-label" for="<?=$form->email->uid?>">Email</label>
							<div class="controls">
								<?=$form->email
												->setAttribute('class', 'span5')
												->setAttribute('placeholder', 'Email')
												->toHtml()
								?>
							</div>
						</div>

						<div class="control-group">
							<label class="control-label" for="<?=$form->bank->uid?>">Bank</label>
							<div class="controls">
								<?=$form->bank
												->setAttribute('class', 'span5')
												->setAttribute('placeholder', 'Kies bank')
												->toHtml()
								?>
							</div>
						</div>

						<div class="form-actions">
						  <button type="submit" class="btn btn-primary">Go to Payment</button>
						  <button type="reset" class="btn">Cancel</button>
						</div>

					</fieldset>
				</form>
			</article>

			<aside class="span3">ASIDE</aside>

		</div>
	</div>

	<footer class="footer">
		<div class="container">
			<p>Designed using Bootstrap</p>
		</div>
	</footer>


</body>
</html>
