<!DOCTYPE html>
<html>
<head>
<?php require_once BASEDIR . 'templates/defaults/head.phtml'; ?>
<title>BitCoin Store</title>
<body>

	<?php require_once BASEDIR . 'templates/defaults/header.phtml'; ?>

	<div class="container">
		<div class="row">

			<article class="span9">
				<form class="form-horizontal" method="POST" novalidate="novalidate">
					<?=$form->formtoken->toHtml()?>
					<fieldset>
						<legend>Order BitCoins</legend>

						<div class="control-group<?=$form->email->validate()?'':' error'?>">
							<label class="control-label" for="<?=$form->email->uid?>">Email</label>
							<div class="controls">
								<?=$form->email
												->setAttribute('class', 'span5')
												->setAttribute('placeholder', 'Email')
												->toHtml()
								?>
								<span class="help-inline"><?=$form->email->getValidationError()?></span>
							</div>
						</div>

						<div class="control-group<?=$form->bank->validate()?'':' error'?>">
							<label class="control-label" for="<?=$form->bank->uid?>">Bank</label>
							<div class="controls">
								<?=$form->bank
												->setAttribute('class', 'span5')
												->setAttribute('placeholder', 'Kies bank')
												->toHtml()
								?>
								<span class="help-inline"><?=$form->bank->getValidationError()?></span>
							</div>
						</div>

						<div class="form-actions">
							<?php
								if ( $next = $form->step->getNextStep() ) {
									echo $next->setAttribute('class', 'btn btn-primary')
														->setAttribute('text', 'Next step')
														->toHtml();
								}
							?>
							<?php
								if ( $next = $form->step->getPreviousStep() ) {
									echo $next->setAttribute('class', 'btn')
														->setAttribute('text', 'Previous step')
														->toHtml();
								}
							?>
						</div>

					</fieldset>
				</form>
			</article>

			<aside class="span3">ASIDE</aside>

		</div>
	</div>

	<?php require_once BASEDIR . 'templates/defaults/footer.phtml'; ?>

</body>
</html>
