<!DOCTYPE html>
<html>
<head>
<?php require_once BASEDIR . 'templates/defaults/head.phtml'; ?>
<title>BitCoin Store</title>
<body>

	<?php require_once BASEDIR . 'templates/defaults/header.phtml'; ?>

	<div class="container">
		<div class="row">

			<article class="span9">
				<form class="form-horizontal" method="POST" novalidate="novalidate">
					<?=$form->formtoken->toHtml()?>
					<fieldset>
						<legend>Order BitCoins</legend>

						<div class="control-group<?=$form->wallet->validate()?'':' error'?>">
							<label class="control-label" for="<?=$form->wallet->uid?>">Wallet</label>
							<div class="controls">
								<?=$form->wallet
												->setAttribute('class', 'span5')
												->setAttribute('placeholder', 'Wallet')
												->toHtml()
								?>
								<span class="help-inline"><?=$form->wallet->getValidationError()?></span>
							</div>
						</div>

						<div class="control-group<?=$form->number->validate()?'':' error'?>">
							<label class="control-label" for="<?=$form->number->uid?>">Bitcoins</label>
							<div class="controls">
								<?=$form->number
												->setAttribute('class', 'span5')
												->setAttribute('placeholder', 'Number of Bitcoins')
												->setAttribute('type', 'text')
												->toHtml()
								?>
								<span class="help-inline"><?=$form->number->getValidationError()?></span>
							</div>
						</div>

						<div class="control-group<?=$form->rate->validate()?'':' error'?>">
							<label class="control-label">Price per bitcoin</label>
							<div class="controls">
								<span class="uneditable-input span5" id="bitcoinsRate">
									<?=$form->rate?>
								</span>
								<span class="help-inline"><?=$form->rate->getValidationError()?></span>
							</div>
						</div>

						<div class="control-group<?=$form->email->validate()?'':' error'?>">
							<label class="control-label" for="<?=$form->email->uid?>">Email</label>
							<div class="controls">
								<?=$form->email
												->setAttribute('class', 'span5')
												->setAttribute('placeholder', 'Email')
												->toHtml()
								?>
								<span class="help-inline"><?=$form->email->getValidationError()?></span>
							</div>
						</div>

						<div class="control-group<?=$form->bank->validate()?'':' error'?>">
							<label class="control-label" for="<?=$form->bank->uid?>">Bank</label>
							<div class="controls">
								<?=$form->bank
												->setAttribute('class', 'span5')
												->setAttribute('placeholder', 'Kies bank')
												->toHtml()
								?>
								<span class="help-inline"><?=$form->bank->getValidationError()?></span>
							</div>
						</div>

						<div class="form-actions">
						  <button type="submit" class="btn btn-primary">Go to Payment</button>
						  <button type="reset" class="btn">Cancel</button>
						</div>

					</fieldset>
				</form>
			</article>

			<aside class="span3">ASIDE</aside>

		</div>
	</div>

	<?php require_once BASEDIR . 'templates/defaults/footer.phtml'; ?>

</body>
</html>
